/* Generated By:JJTree&JavaCC: Do not edit this line. OgnlParserConstants.java */
namespace ognl
{

public abstract class OgnlParserConstants {

  public const int EOF = 0;
  public const int IDENT = 64;
  public const int LETTER = 65;
  public const int DIGIT = 66;
  public const int DYNAMIC_SUBSCRIPT = 67;
  public const int ESC = 71;
  public const int CHAR_LITERAL = 73;
  public const int BACK_CHAR_ESC = 74;
  public const int BACK_CHAR_LITERAL = 76;
  public const int STRING_ESC = 77;
  public const int STRING_LITERAL = 79;
  public const int INT_LITERAL = 80;
  public const int FLT_LITERAL = 81;
  public const int DEC_FLT = 82;
  public const int DEC_DIGITS = 83;
  public const int EXPONENT = 84;
  public const int FLT_SUFF = 85;
 
  public const int DEFAULT = 0;
  public const int WithinCharLiteral = 1;
  public const int WithinBackCharLiteral = 2;
  public const int WithinStringLiteral = 3;

  public static string[] tokenImage = new string []{
		"<EOF>",
		"\",\"",
		"\"=\"",
		"\"?\"",
		"\":\"",
		"\"||\"",
		"\"or\"",
		"\"&&\"",
		"\"and\"",
		"\"|\"",
		"\"bor\"",
		"\"^\"",
		"\"xor\"",
		"\"&\"",
		"\"band\"",
		"\"==\"",
		"\"eq\"",
		"\"!=\"",
		"\"neq\"",
		"\"<\"",
		"\"lt\"",
		"\">\"",
		"\"gt\"",
		"\"<=\"",
		"\"lte\"",
		"\">=\"",
		"\"gte\"",
		"\"in\"",
		"\"not\"",
		"\"<<\"",
		"\"shl\"",
		"\">>\"",
		"\"shr\"",
		"\">>>\"",
		"\"ushr\"",
		"\"+\"",
		"\"-\"",
		"\"*\"",
		"\"/\"",
		"\"%\"",
		"\"~\"",
		"\"!\"",
		"\"is\"",
		"\".\"",
		"\"(\"",
		"\")\"",
		"\"true\"",
		"\"false\"",
		"\"null\"",
		"\"#this\"",
		"\"#root\"",
		"\"#\"",
		"\"[\"",
		"\"]\"",
		"\"{\"",
		"\"}\"",
		"\"@\"",
		"\"new\"",
		"\"$\"",
		"\" \"",
		"\"\\t\"",
		"\"\\f\"",
		"\"\\r\"",
		"\"\\n\"",
		"<IDENT>",
		"<LETTER>",
		"<DIGIT>",
		"<DYNAMIC_SUBSCRIPT>",
		"\"`\"",
		"\"\\\'\"",
		"\"\\\"\"",
		"<ESC>",
		"<token of kind 72>",
		"\"\\\'\"",
		"<BACK_CHAR_ESC>",
		"<token of kind 75>",
		"\"`\"",
		"<STRING_ESC>",
		"<token of kind 78>",
		"\"\\\"\"",
		"<INT_LITERAL>",
		"<FLT_LITERAL>",
		"<DEC_FLT>",
		"<DEC_DIGITS>",
		"<EXPONENT>",
		"<FLT_SUFF>",
	} ;

}
}
