/* Generated By:JJTree: Do not edit this line. OgnlParserTreeConstants.java */

namespace ognl
{

public abstract class OgnlParserTreeConstants : OgnlParserConstants 
{
  public static int JJTVOID = 0;
  public static int JJTSEQUENCE = 1;
  public static int JJTASSIGN = 2;
  public static int JJTTEST = 3;
  public static int JJTOR = 4;
  public static int JJTAND = 5;
  public static int JJTBITOR = 6;
  public static int JJTXOR = 7;
  public static int JJTBITAND = 8;
  public static int JJTEQ = 9;
  public static int JJTNOTEQ = 10;
  public static int JJTLESS = 11;
  public static int JJTGREATER = 12;
  public static int JJTLESSEQ = 13;
  public static int JJTGREATEREQ = 14;
  public static int JJTIN = 15;
  public static int JJTNOTIN = 16;
  public static int JJTSHIFTLEFT = 17;
  public static int JJTSHIFTRIGHT = 18;
  public static int JJTUNSIGNEDSHIFTRIGHT = 19;
  public static int JJTADD = 20;
  public static int JJTSUBTRACT = 21;
  public static int JJTMULTIPLY = 22;
  public static int JJTDIVIDE = 23;
  public static int JJTREMAINDER = 24;
  public static int JJTNEGATE = 25;
  public static int JJTBITNEGATE = 26;
  public static int JJTNOT = 27;
  public static int JJTINSTANCEOF = 28;
  public static int JJTCHAIN = 29;
  public static int JJTEVAL = 30;
  public static int JJTCONST = 31;
  public static int JJTTHISVARREF = 32;
  public static int JJTROOTVARREF = 33;
  public static int JJTVARREF = 34;
  public static int JJTLIST = 35;
  public static int JJTMAP = 36;
  public static int JJTKEYVALUE = 37;
  public static int JJTSTATICFIELD = 38;
  public static int JJTCTOR = 39;
  public static int JJTPROPERTY = 40;
  public static int JJTSTATICMETHOD = 41;
  public static int JJTMETHOD = 42;
  public static int JJTPROJECT = 43;
  public static int JJTSELECT = 44;
  public static int JJTSELECTFIRST = 45;
  public static int JJTSELECTLAST = 46;


  public static string[] jjtNodeName = {
    "void",
    "Sequence",
    "Assign",
    "Test",
    "Or",
    "And",
    "BitOr",
    "Xor",
    "BitAnd",
    "Eq",
    "NotEq",
    "Less",
    "Greater",
    "LessEq",
    "GreaterEq",
    "In",
    "NotIn",
    "ShiftLeft",
    "ShiftRight",
    "UnsignedShiftRight",
    "Add",
    "Subtract",
    "Multiply",
    "Divide",
    "Remainder",
    "Negate",
    "BitNegate",
    "Not",
    "Instanceof",
    "Chain",
    "Eval",
    "Const",
    "ThisVarRef",
    "RootVarRef",
    "VarRef",
    "List",
    "IDictionary",
    "KeyValue",
    "StaticField",
    "Ctor",
    "Property",
    "StaticMethod",
    "Method",
    "Project",
    "Select",
    "SelectFirst",
    "SelectLast",
  };
}
}
