//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Concordion.NET")]
[assembly: AssemblyDescription("Concordion Acceptance Testing Framework")]
[assembly: AssemblyCompany("concordion.org")]
[assembly: AssemblyProduct("Concordion")]
[assembly: AssemblyCopyright("Copyright © concordion.org 2015")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("923eb1d8-0d6a-4a05-896c-16f127f2944f")]
[assembly: AssemblyVersion("0.1.99.9999")]
[assembly: AssemblyFileVersion("0.1.99.9999")]


