//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Concordion.NET")]
[assembly: AssemblyDescription("Concordion Acceptance Testing Framework")]
[assembly: AssemblyCompany("http://code.google.com/p/concordion-net/")]
[assembly: AssemblyProduct("Concordion")]
[assembly: AssemblyCopyright("Copyright © Jeffrey Cameron 2009")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("923eb1d8-0d6a-4a05-896c-16f127f2944f")]
[assembly: AssemblyVersion("0.1.99.9999")]
[assembly: AssemblyFileVersion("0.1.99.9999")]


